services:
  - type: web
    name: php-app
    env: php
    plan: free
    region: oregon
    buildCommand: |
      curl -sS https://getcomposer.org/installer | php
      php composer.phar install
    startCommand: php -S 0.0.0.0:10000
