services:
  - type: web
    name: php-app
    env: php
    plan: free
    region: oregon
    buildCommand: |
      apt-get update
      apt-get install -y php
      curl -sS https://getcomposer.org/installer | php
      php composer.phar install
    startCommand: |
      php -v
      php -S 0.0.0.0:10000
